// Demo/seed data for platform display purposes
// These appear on public pages to make the platform look alive for first visitors

export const demoTrainers = [
  {
    id: "demo-trainer-1",
    slug: "rajesh-kumar",
    user_id: "demo-user-1",
    approval_status: "approved",
    current_role: "Senior Software Engineer",
    current_company: "TCS, Hyderabad",
    skills: ["Python", "Data Science", "Machine Learning"],
    experience_years: 8,
    average_rating: 4.9,
    total_students: 45,
    subscription_plan: "elite",
    teaching_languages: ["Telugu", "English", "Hindi"],
    bio: "I'm a Senior Software Engineer at TCS with 8 years of experience in Python and Machine Learning. I've trained 45+ students and helped many land roles at top tech companies. I believe in hands-on, project-based learning.",
    profile: { full_name: "Rajesh Kumar", city: "Hyderabad" },
    avatarColor: "#1A56DB",
  },
  {
    id: "demo-trainer-2",
    slug: "priya-sharma",
    user_id: "demo-user-2",
    approval_status: "approved",
    current_role: "UI/UX Designer",
    current_company: "Infosys, Bangalore",
    skills: ["Figma", "Adobe XD", "UI Design", "Web Design"],
    experience_years: 5,
    average_rating: 4.8,
    total_students: 32,
    subscription_plan: "pro",
    teaching_languages: ["Hindi", "English"],
    bio: "Creative UI/UX Designer at Infosys with 5 years of experience designing user-centric digital products. Passionate about teaching design thinking and modern tools.",
    profile: { full_name: "Priya Sharma", city: "Bangalore" },
    avatarColor: "#7C3AED",
  },
  {
    id: "demo-trainer-3",
    slug: "mohammed-irfan",
    user_id: "demo-user-3",
    approval_status: "approved",
    current_role: "Full Stack Developer",
    current_company: "Wipro, Chennai",
    skills: ["React", "Node.js", "JavaScript", "MongoDB"],
    experience_years: 6,
    average_rating: 4.7,
    total_students: 28,
    subscription_plan: "pro",
    teaching_languages: ["Tamil", "English", "Urdu"],
    bio: "Full Stack Developer at Wipro with 6 years of experience building scalable web applications. Expert in MERN stack and modern JavaScript.",
    profile: { full_name: "Mohammed Irfan", city: "Chennai" },
    avatarColor: "#059669",
  },
  {
    id: "demo-trainer-4",
    slug: "sneha-reddy",
    user_id: "demo-user-4",
    approval_status: "approved",
    current_role: "Digital Marketing Expert",
    current_company: "Startup, Hyderabad",
    skills: ["SEO", "Social Media", "Google Ads", "Content Marketing"],
    experience_years: 4,
    average_rating: 4.9,
    total_students: 51,
    subscription_plan: "elite",
    teaching_languages: ["Telugu", "Hindi", "English"],
    bio: "Digital Marketing Expert with 4 years of experience helping startups grow online. Specialist in SEO, paid ads, and social media strategy.",
    profile: { full_name: "Sneha Reddy", city: "Hyderabad" },
    avatarColor: "#EA580C",
  },
  {
    id: "demo-trainer-5",
    slug: "arjun-nair",
    user_id: "demo-user-5",
    approval_status: "approved",
    current_role: "CA & Finance Trainer",
    current_company: "Independent, Kerala",
    skills: ["Accounting", "Tally", "GST", "Financial Planning"],
    experience_years: 7,
    average_rating: 4.8,
    total_students: 38,
    subscription_plan: "pro",
    teaching_languages: ["Malayalam", "English", "Hindi"],
    bio: "Chartered Accountant and Finance Trainer with 7 years of experience. Helped 38+ students clear their CA exams and master accounting tools.",
    profile: { full_name: "Arjun Nair", city: "Kochi" },
    avatarColor: "#DC2626",
  },
  {
    id: "demo-trainer-6",
    slug: "divya-menon",
    user_id: "demo-user-6",
    approval_status: "approved",
    current_role: "Communication & Soft Skills Trainer",
    current_company: "Independent, Mumbai",
    skills: ["Public Speaking", "Interview Prep", "Business English", "Personality Development"],
    experience_years: 5,
    average_rating: 4.9,
    total_students: 62,
    subscription_plan: "elite",
    teaching_languages: ["Hindi", "English", "Marathi"],
    bio: "Dedicated Communication and Soft Skills Trainer with 5 years of experience. Helped 62+ students ace interviews and build confidence.",
    profile: { full_name: "Divya Menon", city: "Mumbai" },
    avatarColor: "#0D9488",
  },
];

export const demoCourses = [
  {
    id: "demo-course-1",
    trainerId: "demo-trainer-1",
    title: "Python for Beginners to Advanced",
    duration: "3 months",
    sessions: 24,
    fee: 2999,
    level: "Beginner to Advanced",
    description: "Master Python from scratch. Covers fundamentals, OOP, data structures, libraries like Pandas & NumPy, and real-world projects.",
    curriculum: ["Python Basics & Syntax", "OOP & Data Structures", "Pandas & NumPy", "Machine Learning Intro", "Capstone Project"],
  },
  {
    id: "demo-course-2",
    trainerId: "demo-trainer-2",
    title: "UI/UX Design Masterclass",
    duration: "2 months",
    sessions: 16,
    fee: 1999,
    level: "Beginner to Intermediate",
    description: "Learn UI/UX from scratch using Figma and Adobe XD. Build a complete portfolio with real design projects.",
    curriculum: ["Design Thinking", "Wireframing & Prototyping", "Figma Masterclass", "User Research", "Portfolio Project"],
  },
  {
    id: "demo-course-3",
    trainerId: "demo-trainer-3",
    title: "Full Stack Web Development",
    duration: "4 months",
    sessions: 32,
    fee: 2499,
    level: "Beginner to Advanced",
    description: "Complete MERN stack training — React, Node.js, Express, MongoDB. Build 5+ real projects for your portfolio.",
    curriculum: ["HTML/CSS/JS Fundamentals", "React & State Management", "Node.js & Express API", "MongoDB & Mongoose", "Deployment & DevOps"],
  },
  {
    id: "demo-course-4",
    trainerId: "demo-trainer-4",
    title: "Digital Marketing Complete Course",
    duration: "2 months",
    sessions: 16,
    fee: 1499,
    level: "Beginner",
    description: "Master digital marketing — SEO, Google Ads, social media marketing, content strategy, and analytics.",
    curriculum: ["SEO Fundamentals", "Google Ads & PPC", "Social Media Strategy", "Content Marketing", "Analytics & Reporting"],
  },
  {
    id: "demo-course-5",
    trainerId: "demo-trainer-5",
    title: "Accounting & GST Mastery",
    duration: "2 months",
    sessions: 16,
    fee: 1799,
    level: "Beginner to Intermediate",
    description: "Learn accounting, Tally ERP, GST filing, and financial planning with practical case studies.",
    curriculum: ["Accounting Basics", "Tally ERP 9", "GST Filing & Compliance", "Financial Statements", "Tax Planning"],
  },
  {
    id: "demo-course-6",
    trainerId: "demo-trainer-6",
    title: "Communication & Interview Skills",
    duration: "1 month",
    sessions: 8,
    fee: 999,
    level: "All Levels",
    description: "Build confidence, ace interviews, and master professional communication skills.",
    curriculum: ["Public Speaking", "Interview Preparation", "Business English", "Body Language & Confidence", "Mock Interviews"],
  },
];

export const demoTestimonials = [
  {
    id: "demo-review-1",
    name: "Rahul Verma",
    city: "Hyderabad",
    rating: 5,
    text: "Got placed at Amazon after completing the Python course with Rajesh sir. His teaching style is so practical — every concept tied to real projects. Best investment I've made!",
    course: "Python for Beginners to Advanced",
  },
  {
    id: "demo-review-2",
    name: "Ananya Singh",
    city: "Delhi",
    rating: 5,
    text: "Landed my first freelance project within 2 weeks of completing the UI/UX course. Priya ma'am's portfolio guidance was incredible!",
    course: "UI/UX Design Masterclass",
  },
  {
    id: "demo-review-3",
    name: "Karthik Raju",
    city: "Chennai",
    rating: 5,
    text: "Cleared my CA exam on the first attempt with Arjun sir's guidance. His practical approach to accounting made complex topics simple.",
    course: "Accounting & GST Mastery",
  },
  {
    id: "demo-review-4",
    name: "Pooja Patel",
    city: "Pune",
    rating: 5,
    text: "Got selected in campus interviews at 3 companies after Divya ma'am's communication training. My confidence completely transformed!",
    course: "Communication & Interview Skills",
  },
];

export const demoStats = {
  students: 500,
  trainers: 50,
  avgRating: 4.8,
  successRate: 95,
  sessions: 1200,
  skills: 15,
};

export const isDemo = (id: string) => id.startsWith("demo-");

export const getDemoTrainer = (id: string) => demoTrainers.find((t) => t.id === id);
export const getDemoCourse = (trainerId: string) => demoCourses.filter((c) => c.trainerId === trainerId);
