project_id = "huszmetnqxrividclgad"

[functions.notify-trainer-status]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.process-referral]
verify_jwt = false

[functions.process-trainer-referral]
verify_jwt = false

[functions.smart-reminders]
verify_jwt = false
