
ALTER TABLE public.trainers
  ADD COLUMN IF NOT EXISTS dob date,
  ADD COLUMN IF NOT EXISTS whatsapp text,
  ADD COLUMN IF NOT EXISTS selfie_url text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS pincode text,
  ADD COLUMN IF NOT EXISTS portfolio_url text,
  ADD COLUMN IF NOT EXISTS secondary_skill text,
  ADD COLUMN IF NOT EXISTS work_email text,
  ADD COLUMN IF NOT EXISTS expertise_areas text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS demo_video_url text,
  ADD COLUMN IF NOT EXISTS curriculum_pdf_url text,
  ADD COLUMN IF NOT EXISTS services_offered text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS course_materials text,
  ADD COLUMN IF NOT EXISTS govt_id_type text,
  ADD COLUMN IF NOT EXISTS aadhaar_url text,
  ADD COLUMN IF NOT EXISTS additional_services_details text,
  ADD COLUMN IF NOT EXISTS course_title text,
  ADD COLUMN IF NOT EXISTS course_duration text,
  ADD COLUMN IF NOT EXISTS course_fee numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS course_description text,
  ADD COLUMN IF NOT EXISTS verification_method text,
  ADD COLUMN IF NOT EXISTS verification_value text;
